name: Setup Branch Protection

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  setup-branch-protection:
    runs-on: ubuntu-latest
    permissions:
      administration: write
      contents: write
    steps:
      - name: Setup Branch Protection
        uses: actions/github-script@v7
        with:
          script: |
            try {
              // Get the default branch name
              const repo = await github.rest.repos.get({
                owner: context.repo.owner,
                repo: context.repo.repo
              });
              
              const defaultBranch = repo.data.default_branch;
              
              console.log(`Setting up branch protection for ${defaultBranch}`);
              
              // Set up branch protection rules
              await github.rest.repos.updateBranchProtection({
                owner: context.repo.owner,
                repo: context.repo.repo,
                branch: defaultBranch,
                required_status_checks: {
                  strict: true,
                  contexts: ['PR Description Validation']
                },
                enforce_admins: false,
                required_pull_request_reviews: {
                  required_approving_review_count: 1,
                  dismiss_stale_reviews: true,
                  require_code_owner_reviews: false
                },
                restrictions: null,
                allow_force_pushes: false,
                allow_deletions: false
              });
              
              console.log('Branch protection rules applied successfully');
            } catch (error) {
              console.error('Error setting up branch protection:', error.message);
              // Don't fail the workflow if branch protection setup fails
              // (this might happen if the action doesn't have admin permissions)
            } 